apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: forecastappfeature
    dynatrace.com/guardian-tags: 'service=forecastappfeature'
  name: feature
  description: forecastapp
  dynatrace:
    queries:
      - id: Logs
        description: Fetch Logs
        query: >
          fetch logs, from: -24h
                | filter matchesValue(k8s.deployment.name, "forecastappfeature-*")
                | sort timestamp desc
                | fieldsAdd content=if(isNull(content), "N/A", else: content)
                | fieldsAdd loglevel=if(isNull(loglevel), "N/A", else: loglevel)
                | fieldsAdd source=if(isNull(log.source), "N/A", else: log.source)
                | fieldsAdd host=if(isNull(host.name), "N/A", else: host.name)
                | fieldsAdd environment = "lvo35023"
                | fieldsKeep timestamp, source, content, loglevel, host, environment
  links:
    - url: http://localhost:8889
      title: launch app
      icon: dashboard
spec:
  lifecycle: experimental
  owner: guests
  type: service
