apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: forecastappfeature
  name: feature
  description: forecastapp
  links:
    - url: http://localhost:8889
      title: launch app
      icon: dashboard
spec:
  lifecycle: experimental
  owner: guests
  type: service
